<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE address
[
   <!ELEMENT address (name,company,phone)>
   <!ELEMENT name (#PCDATA)>
   <!ELEMENT company (nameinc, iso)>
   <!ELEMENT nameinc (#PCDATA)>
   <!ELEMENT iso (#PCDATA)>
   <!ELEMENT phone (#PCDATA)>
]>

<address>
   <name>Tanmay Patil</name>
   <company>
    <nameinc>TutorialsPoint</nameinc>
    <iso> yes</iso>
   </company>
   <phone>(011) 123-4567</phone>
</address>